version: 2
jobs:
  build:
    working_directory: ~/procman
    docker:
      - image: circleci/node:9-browsers
    steps:
      - checkout
      - run: (cd app && yarn && yarn build)
      - persist_to_workspace:
          root: app/dist
  build_server:
    working_directory: /go/src/github.com/uphy/procman
    docker:
      - image: circleci/golang:1.9
    steps:
      - attach_workspace:
          at: app/dist
      - checkout
      - run: go get github.com/rakyll/statik -src app/dist
      - run: statik
      - run: go get github.com/mitchellh/gox
      - run: gox --osarch "linux/386 linux/amd64 darwin/386 darwin/amd64" --output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}/{{.Dir}}"
      - run: |
          pushd .
          cd dist
          for dir in $(ls -1)
          do
            tar czf $dir.tar.gz $dir
            rm -rf $dir
          done
          popd
      - run: go get github.com/tcnksm/ghr
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -delete 0.0.1 dist/
workflows:
  version: 2
  build:
    jobs:
      - build:
      - build_server:
          requires:
            - build
